import Head from "next/head";
import { useQuery } from "@tanstack/react-query";
import { Box, Stack } from "@mantine/core";
import request from "axios";
import { UserList, UserForm } from "@/components";

export default function Home() {
  const { isLoading, error, data } = useQuery({
    queryKey: ["users"],
    queryFn: () => {
      return request.get("./api/user").then((res) => {
        return res.data;
      });
    },
  });

  return (
    <>
      <Head>
        <title>Prisma Mock</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{ maxWidth: 300 }} mx={"auto"}>
          <Stack>
            <UserForm />
            {isLoading ? <Box>Loading...</Box> : ""}
            {error ? <Box>Error: {JSON.stringify(error)}</Box> : ""}
            {data ? <UserList users={data} /> : ""}
          </Stack>
        </Box>
      </main>
    </>
  );
}
